# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b300822a398c1993d320f00f57e2ecbf0cf2b50738460c98dd1093737d2bf372949d74827cfdde487889e9c991ebe11bc92156ac042d657a258ffe35c19db3bf

test:
  secret_key_base: 8acc61837373947a5a185d4093756506b038a6077633fa9e61b52779aca999773d81adbd11b55c5045daaeb9601df6cf46f3aa81b2f796f50c5d8f840d692bad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
